### ISSUE TITLE
Not an Avro data file

### ISSUE THREAD

**Issue by martinplank** [confluentinc/kafka-connect-hdfs#410] opened 2019-02-04 12:00 UTC
We are using kafka-connect-hdfs 5.0.0.

After few weeks of running HDFS connector, we found this issue in the log:
```
org.apache.kafka.connect.errors.DataException: java.io.IOException: Not an Avro data file
        at io.confluent.connect.hdfs.avro.AvroFileReader.getSchema(AvroFileReader.java:51)
        at io.confluent.connect.hdfs.avro.AvroFileReader.getSchema(AvroFileReader.java:33)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:344)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Not an Avro data file
        at org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:50)
        at io.confluent.connect.hdfs.avro.AvroFileReader.getSchema(AvroFileReader.java:46)
        ... 15 more
```
Connector and its task was in RUNNING state, but failed to write any data because of this error.

After looking at HDFS, we found an empty (zero size) Avro file in the topics directory:
```
-rw-rw-r--   3 hive hive          0 2019-01-28 14:30 /topics/mytopic/p=2019-01-24/mytopic+0+0010710455+0010710554.avro
```

We fixed the issue by deleting this empty file and restarting the connector.

What caused creating this empty file on HDFS?

Connector configuration:
```
name=mytopic-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=mytopic
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=...
schema.compatibility=BACKWARD
hdfs.url=...
hadoop.conf.dir=/etc/hadoop/conf
hadoop.home=/opt/cloudera/parcels/CDH/lib/hadoop
topics.dir=/topics
logs.dir=/logs
format.class=io.confluent.connect.hdfs.avro.AvroFormat
flush.size=100
rotate.interval.ms=60000
hive.integration=true
hive.metastore.uris=...
hive.conf.dir=/etc/hive/conf
hive.home=/opt/cloudera/parcels/CDH/lib/hive
hive.database=...
hdfs.authentication.kerberos=true
connect.hdfs.principal=...
connect.hdfs.keytab=...
hdfs.namenode.principal=...
partitioner.class=io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner
partition.duration.ms=86400000
path.format='p'=yyyy-MM-dd
locale=sk_SK
timezone=Europe/Bratislava
timestamp.extractor=RecordField
timestamp.field=TIMESTAMP
transforms=...
```

**Comment by kalyan57** [comment] 2019-05-08 06:33
I'm joining with just the same issue with this version of kafka-connect!
The problem emerges from time to time.
What kind of additional information is necessary for investigation?

**Comment by ncliang** [comment] 2019-10-03 20:37
Duplicate of #453

**Closed by ncliang** 2019-10-03 20:37 UTC
