### ISSUE TITLE
rotate.interval.ms not take effect as expected

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/kafka-connect-hdfs#231] opened 2017-09-26 10:38 UTC
I have a small table within 100 rows, and I set flush.size=10000, when sync from mysql to hdfs/hive I found the small table data file won't be closed and commit. Thus I can't query the small table from hive. Here is my hdfs.properties file

name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=5
topics=small_table
hdfs.url=hdfs://localhost:9000
logs.dir=/kafka-connect/logs
topics.dir=/kafka-connect/topics
flush.size=10000
rotate.interval.ms=10000
hive.metastore.uris=thrift://localhost:9083
hive.integration=true
hive.database=kafka-connect
schema.compatibility=BACKWARD

**Comment by kkonstantine** [comment] 2017-10-11 22:00
There's nothing in your configuration that implies that hdfs connector won't roll a file, even if you have just a few records. 

Have you confirmed that you have the records in Kafka, on this specific topic you are trying to export? You may use one of the console consumer commands from the command line to do this while the connector is running.

**Comment by kkonstantine** [comment] 2017-10-27 21:31
Since it's been a while since this issue was reported and there was no update in the meantime I'm closing the issue. Feel free to re-open if this issue persists.

**Closed by kkonstantine** 2017-10-27 21:31 UTC
