### ISSUE TITLE
Issue when trying to use hdfs connector for azure data lake

### ISSUE THREAD

**Issue by sumitbaurai** [confluentinc/kafka-connect-hdfs#358] opened 2018-08-03 14:13 UTC
Confluent version : 4.1.1
Hadoop version : 3.1

While trying to move data from kafka to azure data lake, I configured the connector with the following : 

name=hdfs-sink
hadoop.conf.dir=/<path-to-hadoop>/hadoop-3.1.0/etc/hadoop
hadoop.home=/<path-to-hadoop>//hadoop-3.1.0
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=test_azure
format.class=io.confluent.connect.hdfs.string.StringFormat
topics.dir=kafka
#hdfs.url=hdfs://localhost:8020
store.url=adl://myurl.azuredatalakestore.net/
#store.url=hdfs://localhost:8020
hdfs.url=adl://myurl.azuredatalakestore.net/
flush.size=3

Also copied all the jars from <hadoop>/share/hadoop/tools/lib to confluent-4.1.1/share/java/kafka-connect-hdfs. 

But upon loading the connector, it is throwing the error : 

Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.reloadExistingConfigurations()V
	at org.apache.hadoop.fs.adl.AdlConfKeys.addDeprecatedKeys(AdlConfKeys.java:126)

Full Stack trace

[2018-08-03 15:53:27,656] INFO Couldn't start HdfsSinkConnector: (io.confluent.connect.hdfs.HdfsSinkTask:90)
org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:56)
	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:213)
	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
	at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:82)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:51)
	... 12 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.reloadExistingConfigurations()V
	at org.apache.hadoop.fs.adl.AdlConfKeys.addDeprecatedKeys(AdlConfKeys.java:126)
	at org.apache.hadoop.fs.adl.AdlFileSystem.<clinit>(AdlFileSystem.java:98)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2691)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:420)
	at io.confluent.connect.hdfs.storage.HdfsStorage.<init>(HdfsStorage.java:56)
	... 17 more

This does look like a version mismatch, but I am not sure, which hadoop version is compatible with the connector version. 

Any pointers are highly appreciated ..

**Comment by kkonstantine** [comment] 2018-09-19 04:14
Will close this ticket as duplicate of: https://github.com/confluentinc/kafka-connect-hdfs/issues/333 

Azure is not explicitly supported currently, but the above ticket describes a workaround with the required missing dependencies that need to be copied. Keeping open that ticket until a transparent integration is added.

**Closed by kkonstantine** 2018-09-19 04:14 UTC
