### ISSUE TITLE
NullPointerException when using RegexRouter

### ISSUE THREAD

**Issue by cricket007** [confluentinc/kafka-connect-hdfs#236] opened 2017-09-29 22:13 UTC
I would like to drop the `.global` (or `_global`) suffix from a topic for landing in HDFS and creating a Hive table. I was reading over on [this blog post](https://www.confluent.io/blog/simplest-useful-kafka-connect-data-pipeline-world-thereabouts-part-3/) that SMT would be the way to go, but that isn't working for me. 

Is this config section correct? 

```json
    "topics": "fooBar.global",

    "_comment": "===== We just want the base topic name for all topics. Works for non-global topics too =====",
    "transforms":"dropGlobal",
    "transforms.dropGlobal.type":"org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.dropGlobal.regex": "([a-zA-Z0-9\\-_]+)[._]global$",
    "transforms.dropGlobal.replacement":"$1",
```

If so, why would I get this error, only when adding the transform?

```java
[2017-09-29 21:49:41,186] (pool-1-thread-4) ERROR - org.apache.kafka.connect.runtime.WorkerSinkTask - Task kafkaconnect-hdfs-laptop-fooBar_transform threw an uncaught and unrecoverable exception
java.lang.NullPointerException
	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:211)
	at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:103)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-09-29 21:49:41,191] (pool-1-thread-4) ERROR - org.apache.kafka.connect.runtime.WorkerSinkTask - Task is being killed and will not recover until manually restarted
[2017-09-29 21:49:41,192] (pool-1-thread-4) ERROR - org.apache.kafka.connect.runtime.WorkerTask - Task kafkaconnect-hdfs-laptop-fooBar_transform threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:451)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-09-29 21:49:41,194] (pool-1-thread-4) ERROR - org.apache.kafka.connect.runtime.WorkerTask - Task is being killed and will not recover until manually restarted
[2017-09-29 21:49:41,195] (pool-1-thread-4)  INFO - io.confluent.connect.hdfs.DataWriter - Shutting down Hive executor service.
[2017-09-29 21:49:41,195] (pool-1-thread-4)  INFO - io.confluent.connect.hdfs.DataWriter - Awaiting termination.
```

Thanks!

**Comment by cricket007** [comment] 2017-10-02 15:07
@kkonstantine I found this JIRA. https://issues.apache.org/jira/browse/KAFKA-5567
And pull https://github.com/apache/kafka/pull/3499/files 

Is it related to this issue? Renaming the topic is causing this Hashmap to not find the original topic? 

```java
  public void write(Collection<SinkRecord> records) {
    for (SinkRecord record: records) {
      String topic = record.topic();
      int partition = record.kafkaPartition();
      TopicPartition tp = new TopicPartition(topic, partition);
      topicPartitionWriters.get(tp).buffer(record); // <-------- Line 211
    }
```

**Comment by kkonstantine** [comment] 2017-10-11 21:17
@cricket007 that would be my guess too, off the top of my head. 

Have you been able to confirm that this is not an issue with an AK Connect that includes the fix?

**Comment by cricket007** [comment] 2017-10-12 00:15
Sorry, can you clarify "AK Connect"?

**Comment by cricket007** [comment] 2017-10-12 00:22
Assuming "Apache Kafka Connect", I'm using a Docker container for CP 3.2.2 pulled out of a private repository. I can see what I can do to build/download the latest CP, sure.

I'm not in a position to upgrade the Kafka cluster, though, if needed.

**Comment by kkonstantine** [comment] 2017-10-12 04:18
Yes, that is correct, I was referring to the Connect workers. The workers need to be upgraded to a version that includes the fix. Not the Kafka brokers.

**Comment by kkonstantine** [comment] 2017-11-02 18:48
Closing this ticket since it seems it's been fixed in [KAFKA-5567](https://issues.apache.org/jira/browse/KAFKA-5567)

**Closed** 2017-11-02 18:48 UTC

**Comment by cricket007** [comment] 2018-04-28 16:25
@cadl I ended up using a custom Partitioner subclass to solve my problem.

I don't remember why, but I had realized RegexRouter didn't do exactly what I needed.

**Comment by 4bz** [comment] 2019-01-23 16:19
@kkonstantine @cricket007,

I am getting a NullPointerException when using RegexRouter on confluent platform v5.1.0 env. In @cadl post above he seems to suggest he also encountered this issue. Does this ticket need re-opened or is there a fix/alternative other than writing a custom Partitioner?

**Comment by cricket007** [comment] 2019-01-23 16:28
AFAIK, `topicPartitionWriters.get(tp)` is the problem, and has not changed. That Hashmap doesn't contain the renamed the topic-partition of the regex application.

I filed my findings, which I believe are part of the same problem, here https://github.com/confluentinc/kafka-connect-storage-common/issues/91

**Comment by hoesler** [comment] 2019-03-12 17:20
I think the problem is, that the `topicPartitionWriters` get initialized in [`SinkTask#open`](https://github.com/confluentinc/kafka-connect-hdfs/blob/v5.1.2/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L421) before any message has been seen. 
The RegexRouter, like all SMTs, work on messages. So a partition writer should either accept a topic argument, or must be created (or fetched from a cache) for each message.

This problem seems to be an issue is several Sinks: https://github.com/confluentinc/kafka-connect-elasticsearch/pull/275

**Comment by hoesler** [comment] 2019-03-13 09:54
**Update**: I altered the code to create `TopicPartitionWriter`s for record topics. This leads to another problem, however, as the sink [talks back to kafka](https://github.com/confluentinc/kafka-connect-hdfs/blob/6bba46327dc0b67eb51bc7dbd5ace2deb12c3783/src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java#L565), which has no notion of the modified topic name. It seems that the hdfs sink and the regex router are conceptually incompatible.
