### ISSUE TITLE
Recovery persistently fails due to empty WAL file  

### ISSUE THREAD

**Issue by vikeshkhanna** [confluentinc/kafka-connect-hdfs#53] opened 2016-05-04 21:38 UTC
We noticed that two partitions of one of our topics had an ever increasing offset lag. This was happening because Kafka Connect persistently failed to recover these two partitions. We get the following error every time in the log4j files:

```
[2016-05-04 17:30:02,865] ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED (io.confluent.connect.hdfs.TopicPartitionWriter:221)
org.apache.kafka.connect.errors.ConnectException: Error creating writer for log file hdfs://bikeshed//kafka_connect/logs/goscribe.mp-hash_events/48/log
    at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
    at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
    at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:448)
    at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:204)
    at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:236)
    at io.confluent.connect.hdfs.DataWriter.onPartitionsAssigned(DataWriter.java:299)
    at io.confluent.connect.hdfs.HdfsSinkTask.onPartitionsAssigned(HdfsSinkTask.java:103)
    at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:362)
    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:194)
    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:225)
    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.ensurePartitionAssignment(ConsumerCoordinator.java:311)
    at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:890)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:853)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:171)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readFully(DataInputStream.java:169)
    at io.confluent.connect.hdfs.wal.WALFile$Reader.init(WALFile.java:590)
    at io.confluent.connect.hdfs.wal.WALFile$Reader.initialize(WALFile.java:558)
    at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:535)
    at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:214)
    at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:67)
    at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)
    ... 16 more
```

The log directory on HDFS looks like this:

```
vikesh@sjc8c-rm9-15d ~ $ hadoop fs -ls hdfs://bikeshed//kafka_connect/logs/goscribe.mp-hash_events/48/
Found 2 items
-rw-r--r--   3 hadoop hadoop          0 2016-05-02 08:25 hdfs://bikeshed/kafka_connect/logs/goscribe.mp-hash_events/48/log
-rw-r--r--   3 hadoop hadoop        358 2016-05-02 07:03 hdfs://bikeshed/kafka_connect/logs/goscribe.mp-hash_events/48/log.1
```

The WALFile Reader fails to read the empty WAL file (/log). My understanding of what happened is the following:

Connect calls `truncate` during recovery, which deletes log.1 file and then renames the log file to log.1. At this point, there is no log file. Once the recovery is finished and one partition has been written, it creates the log file and writes it:
1. Create log file (https://github.com/confluentinc/kafka-connect-hdfs/blob/6e7395bd9c8c2e0e921d65650d92bdbe574563b0/src/main/java/io/confluent/connect/hdfs/wal/WALFile.java#L224) 
2. Write version header etc.: https://github.com/confluentinc/kafka-connect-hdfs/blob/6e7395bd9c8c2e0e921d65650d92bdbe574563b0/src/main/java/io/confluent/connect/hdfs/wal/WALFile.java#L264

If the process gets killed between 1 and 2, this would happen.

**Resolution:** We manually deleted the log file and observed that the recovery proceeded normally. I believe that's the case because FSWAL checks for a non-existent log file (but not an empty log file, which is clearly possible): https://github.com/confluentinc/kafka-connect-hdfs/blob/6e7395bd9c8c2e0e921d65650d92bdbe574563b0/src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java#L102

**Comment by Ishiihara** [comment] 2016-05-04 22:37
@vikeshkhanna Thanks for reporting this.  I agree with your analysis. I will try to provide a fix soon.

**Comment by vikeshkhanna** [comment] 2016-05-05 00:01
Thanks @Ishiihara! 

For now, our temporary fix is to add the following in the `apply` method of `FSWAL.java`:

```
if (!storage.exists(logFile)) {
                return;
            }
            // NB: We need to fork this file to fix the race condition described here:
            // https://github.com/confluentinc/kafka-connect-hdfs/issues/53
            // The issue is that an empty log file might be created (connect process killed before
            // header could be written) due to which the recovery persistently fails.
            FileStatus[] statuses = storage.listStatus(logFile);

            if (statuses.length != 1) {
                throw new AssertionError(String.format(
                        "Expected one log file at path: %s. Found multiple files.", logFile
                    )
                );
            }

            // There can only be one log file. So this is safe.
            if (statuses[0].getLen() == 0) {
                log.warn(String.format("Found empty log file at path: %s", logFile));
                return;
            }
```

**Comment by mmiladinovic** [comment] 2016-10-23 10:09
hey guys - any plans to fix this bug in the upcoming release?

**Comment by krisskross** [comment] 2017-04-21 09:16
Any news? We are having this problem as well.

**Comment by blbradley** [comment] 2017-05-11 16:13
I have encountered this in 3.2.1 for all topics in a task and was able to proceed by deleting the WALs for the topics involved. @vikeshkhanna Thanks for mentioning the manual resolution.

**Comment by jumbo007** [comment] 2017-05-30 13:17
We have been getting this error "RECOVERY_PARTITION_PAUSED" (io.confluent.connect.hdfs.TopicPartitionWriter:221)
org.apache.kafka.connect.errors.ConnectException: Error creating writer for log file "hdfs://abc:9000/logs/topicname/55/log.
But we dont see two log files. (I checked a few erroneous log paths but couldnt find two files as log and log.1).
What is the fix for this error as it results into data loss while running Kafka Connect's High Availability.

**Comment by chenchik** [comment] 2017-06-23 20:47
I was able to resolve this issue by removing /logs/my-topic/0/log from hdfs.

**Comment by RohitIndia** [comment] 2018-02-08 10:38
Facing the below error , can you please help on it

2018-01-30 13:19:55,432 [pool-1-thread-45] ERROR (TopicPartitionWriter.java:229) - Recovery failed at state RECOVERY_PARTITION_PAUSED
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: Filesystem closed
        at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:131)
        at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:484)
        at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:212)
        at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:239)
        at io.confluent.connect.hdfs.DataWriter.open(DataWriter.java:281)
        at io.confluent.connect.hdfs.HdfsSinkTask.open(HdfsSinkTask.java:116)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:476)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1000(WorkerSinkTask.java:56)
        at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:512)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:255)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:339)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:303)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:286)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1030)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:995)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:360)

**Comment by Minutis** [comment] 2018-03-28 13:00
All the errors mentioned before are happening to us too:
```
2018-03-28 14:54:57,847 [pool-1-thread-181] ERROR (WALFile.java:177) - Failed creating a WAL Writer: failed to create file /somepath/1/log for DFSClient_NONMAPREDUCE_1297863391_6675 for client 0.0.0.0 because pendingCreates is non-null but no leases found.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:3241)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:3058)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:3343)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:3307)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:621)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.append(AuthorizationProviderProxyClientProtocol.java:129)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:433)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2226)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2222)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2220)

```

```
2018-03-28 14:54:54,491 [pool-1-thread-90] ERROR (TopicPartitionWriter.java:403) - Exception on topic partition topic-1: 
org.apache.kafka.connect.errors.ConnectException: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:97)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:647)
        at io.confluent.connect.hdfs.TopicPartitionWriter.closeTempFile(TopicPartitionWriter.java:654)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:386)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.error(ParquetFileWriter.java:182)
        at org.apache.parquet.hadoop.ParquetFileWriter$STATE.startBlock(ParquetFileWriter.java:174)
        at org.apache.parquet.hadoop.ParquetFileWriter.startBlock(ParquetFileWriter.java:284)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:166)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:109)
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:302)
        at io.confluent.connect.hdfs.parquet.ParquetRecordWriterProvider$1.close(ParquetRecordWriterProvider.java:95)
        ... 16 more
```


```
2018-03-28 14:54:51,679 [pool-1-thread-181] ERROR (TopicPartitionWriter.java:277) - Recovery failed at state RECOVERY_PARTITION_PAUSED
org.apache.kafka.connect.errors.ConnectException: Cannot acquire lease after timeout, will retry.
        at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:95)
        at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
        at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:601)
        at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
        at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:321)
        at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
        at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Using confluent 4.0.0.

**Comment by mikeskali** [comment] 2018-06-13 14:23
This is open since 2016. We experience this frequently in different clusters. we used all version between confluent 3.0.0 till the latest 4.1.1.

This connector is not production ready.

**Comment by kaushiksrinivas** [comment] 2018-07-05 05:29
Having similar error,

stack trace : 
ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED (io.confluent.connect.hdfs.TopicPartitionWriter)
org.apache.kafka.connect.errors.DataException: Error creating writer for log file hdfs://xxxx/xxxx/xxx/performance/kconnectdcos/logs/kcatalog_sales/29/log
               at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
               at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
               at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:601)
               at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:256)
               at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:321)
               at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:374)
               at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:101)
               at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
               at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
               at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
               at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
               at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
               at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
               at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
               at java.io.DataInputStream.readFully(DataInputStream.java:197)
               at java.io.DataInputStream.readFully(DataInputStream.java:169)
               at io.confluent.connect.hdfs.wal.WALFile$Reader.init(WALFile.java:562)
               at io.confluent.connect.hdfs.wal.WALFile$Reader.initialize(WALFile.java:529)
               at io.confluent.connect.hdfs.wal.WALFile$Reader.<init>(WALFile.java:445)
               at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:158)
               at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:75)
               at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)
               ... 17 more

Our log folder has only one log(/log) file with 0 file size.
Any update on this issue ?

**Comment by C0urante** [comment] 2018-07-24 22:38
Addressed by https://github.com/confluentinc/kafka-connect-hdfs/pull/348

**Closed by C0urante** 2018-07-24 22:38 UTC
Labels: bug
