### ISSUE TITLE
Hive integration - table not created on time

### ISSUE THREAD

**Issue by kijanowski** [confluentinc/kafka-connect-hdfs#272] opened 2018-01-10 15:40 UTC
I'm running the Confluent 3.3.0 hdfs connector with hive integration and getting this error:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.confluent.connect.hdfs.errors.HiveMetaStoreException: Invalid partition for default.connecttest7: partition=0
	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:296)
.
.
.
Caused by: InvalidObjectException(message:default.connecttest7 table not found)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$append_partition_by_name_with_environment_context_result$append_partition_by_name_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:51619)
```

As far as I understand it, the table is created in syncwithHive():
https://github.com/confluentinc/kafka-connect-hdfs/blob/3.3.x/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L255

syncWithHive is called by:
https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java#L135
which is called in start():
https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java#L135

Now the problem is, that start(), called by the Connect framework, is called before open(). But it is open(), which assigns topic partitions to assignment. Therefore when start() is called, there are no topic partitions and the connector does not create the required table.
As per the documentation:
"After initialization, Connect will assign the task a set of partitions using open(Collection). These partitions are owned exclusively by this task until they have been closed with close(Collection)."

Is this a bug or rather a PEBKAC? I had to tweak the DataWriter "slightly" since I want to use the connector in a not-so-common environment and I wonder if I messed up something and the vanilla connector works as expected.

**Comment by kijanowski** [comment] 2018-01-17 07:48
One thing worth to note is that this is only an issue, if I start the connector and there are already some messages in the topic. Then it fails since the connector tries to append partitions to a table which does not exist.

However if the topic is empty, the connector starts just fine and when I then add a message, the table is created successfully, partitions are appended and it just works.

**Comment by maurodoglio** [comment] 2018-01-17 15:02
@kijanowski can you try to delete the topic folder on hdfs? I faced the same issue yesterday and doing that seems to fix it.

**Comment by fabiohecht** [comment] 2018-10-24 06:39
Is there a patch or workaround for this issue?

**Comment by RossierFl** [comment] 2018-11-06 14:23
Does someone actually manage to resolve this issue ? We have a blocker on this one. The solution of removing all the topic folder on HDFS isn't really a solution in productive environment. We are running the 5.0.0 HDFS connectors. Or just a contact with someone that could help us about this issue ?

**Comment by serssp** [comment] 2019-02-01 17:41
This patch really re-creates the tables after accidentally deleting them. However, this code caused the connector to stop after some time.
@kijanowski You can launch a connector with this code, but after the tables are created, roll back it.

**Comment by RossierFl** [comment] 2019-02-04 08:31
So this patch shouldn't be merged right ? I will try to take some times to propose somethings that really solve the issue.

**Comment by ykmarupudi12** [comment] 2019-03-14 09:12
Hi there , i am facing the same issue not been able to create hive tables. also tried the work arounds but no luck any help would be much appreciated 

WARN Hive database already exists: default (io.confluent.connect.storage.hive.HiveMetaStore:171)
[2019-03-14 22:05:36,890] ERROR Creating Hive table threw unexpected error (io.confluent.connect.hdfs.TopicPartitionWriter:789)
io.confluent.connect.storage.errors.HiveMetaStoreException: Hive MetaStore exception
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:98)
        at io.confluent.connect.storage.hive.HiveMetaStore.createTable(HiveMetaStore.java:222)
        at io.confluent.connect.hdfs.avro.AvroHiveUtil.createTable(AvroHiveUtil.java:59)
        at io.confluent.connect.hdfs.hive.HiveUtil.createTable(HiveUtil.java:49)
        at io.confluent.connect.hdfs.DataWriter$3.createTable(DataWriter.java:299)
        at io.confluent.connect.hdfs.TopicPartitionWriter$1.call(TopicPartitionWriter.java:787)
        at io.confluent.connect.hdfs.TopicPartitionWriter$1.call(TopicPartitionWriter.java:783)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: MetaException(message:User krish does not have privileges for CREATETABLE)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:29983)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:29951)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:29877)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1075)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1061)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2051)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:670)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:658)
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:152)
        at com.sun.proxy.$Proxy53.createTable(Unknown Source)
        at io.confluent.connect.storage.hive.HiveMetaStore$5.call(HiveMetaStore.java:206)
        at io.confluent.connect.storage.hive.HiveMetaStore$5.call(HiveMetaStore.java:202)
        at io.confluent.connect.storage.hive.HiveMetaStore.doAction(HiveMetaStore.java:96)
        ... 10 more
[2019-03-14 22:05:36,894] ERROR Altering Hive schema threw unexpected error (io.confluent.connect.hdfs.TopicPartitionWriter:804)

**Comment by RossierFl** [comment] 2019-03-14 14:49
Hi,
The work around works ! 
Read the error message that you got, the principal that you are using to connect to HDFS doesn't have enough rights to do it. 
It has nothing to do with the proposed workaround. 

```
Caused by: MetaException(message:User krish does not have privileges for CREATETABLE)
```
BR !

**Comment by ykmarupudi12** [comment] 2019-03-14 19:24
@RossierFl  thanks for your reply. though the error was misleading as i am able to create table. i have also successfully created a hive table on a nonsecure cluster. i guess i have to go back my admins Thanks alot :)

**Comment by mylittlecabin** [comment] 2019-09-14 04:15
v5.3.1 still have this problem

**Comment by exherb** [comment] 2020-08-06 09:04
use this code to restore table

```java
         HdfsSinkConnectorConfig config = new HdfsSinkConnectorConfig(new HashMap<String, String>() {{
            put("store.url", hdfsUrl);
            put("topics", topic);
            put("flush.size", "1000");
            put("hive.integration", "true");
            put("hive.metastore.uris", "thrift://localhost:9083");
            put("timestamp.extractor", "RecordField");
            put("timestamp.field", "timestamp");
            put("timezone", "Asia/Shanghai");
            put("locale", "zh_CN");
        }});
        ParquetHiveUtil hiveUtil = new ParquetHiveUtil(config, new HiveMetaStore(config.getHadoopConfiguration(), config));
        DataWriter.PartitionerWrapper partitioner = new DataWriter.PartitionerWrapper(new HourlyPartitioner());
        partitioner.configure(new HashMap<>(config.plainValues()));
        hiveUtil.createTable("default", topic, schema, partitioner);
```

**Comment by dosvath** [comment] 2021-05-20 21:20
Fixed by https://github.com/confluentinc/kafka-connect-hdfs/pull/568

**Closed by dosvath** 2021-05-20 21:20 UTC
