### ISSUE TITLE
Cann't  use name of schema to detect "logical type"

### ISSUE THREAD

**Issue by xianzhen** [confluentinc/kafka-connect-hdfs#78] opened 2016-06-15 05:37 UTC
Cann't  use name of schema to detect "logical type", Cause it's the name of column with hive support.

**Comment by Ishiihara** [comment] 2016-07-13 19:59
@xianzhen I think we are using the field name in Connect schema as the column name. The name field of a schema can be used to detect logical type. Does this make sense?

**Comment by xianzhen** [comment] 2016-07-14 01:34
Thanks. 
I need a column in hive like this: {\"name\": \"sesssionTime\", \"type\": \"timestamp\"}. I can't make it if kafka use name to detect logical type.

**Comment by Ishiihara** [comment] 2016-07-18 18:49
@xianzhen Thanks for the clarification. This issue is the same as https://github.com/confluentinc/kafka-connect-hdfs/issues/49.

**Comment by Ishiihara** [comment] 2016-07-18 18:49
Close this as it is a duplicate of #49

**Closed by Ishiihara** 2016-07-18 18:49 UTC
