### ISSUE TITLE
Issues related to NullPointerExceptions handling done in DataWriter.java class.

### ISSUE THREAD

**Issue by kaushiksrinivas** [confluentinc/kafka-connect-hdfs#552] opened 2021-03-16 09:13 UTC
We see below PRs focussing on avoiding NPEs in DataWriter class.
1. https://github.com/confluentinc/kafka-connect-hdfs/pull/422
2. https://github.com/confluentinc/kafka-connect-hdfs/pull/496

In case of the first PR, the NPEs were handled via clearing up the 
topicPartitionWriters set as well as the assignment upon close().

With the changes of 2.  https://github.com/confluentinc/kafka-connect-hdfs/pull/496 we see that the code in lines 384 to 410 ( for (String topic : topics ...)in https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/DataWriter.java are never hit as topicpartitionwriters is always empty.
Is this by design or an unintended side effect.

We had reported another issue in lines 401 to 408 https://github.com/confluentinc/kafka-connect-hdfs/issues/538 due to which connector goes into irrecoverable crash loop. So this problem stays hidden with the above changes and hence reporting this query/issue.

**Comment by kaushiksrinivas** [comment] 2021-03-16 09:15
@levzem @gharris1727 
relates to https://github.com/confluentinc/kafka-connect-hdfs/pull/496

**Comment by dosvath** [comment] 2021-03-16 17:33
Hi @kaushiksrinivas the `topicPartitionWriters` are initialized in the constructor [here](https://github.com/confluentinc/kafka-connect-hdfs/blob/abce5cffb350236a8b5021be5e5d6f62b9df5b10/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L327) and `syncwithHive()` that contains the lines you mention is called after the initialization, so I wouldn't see how the writers would always be empty. Are you referring to a specific case? Could you clarify the flow of logic that would end up having the writers empty?

**Comment by kaushiksrinivas** [comment] 2021-03-17 05:13
Hi @dosvath 
Below is the code flow. 
Install worker, install connector. Write few records to hdfs (complete the flush size and commit the file).
Now if we restart the connector, we always see the topicpartitionwriters to be empty in syncwithhive.

we have put debug statements in syncwithhive() and never observed topicpartitionwriters to be non empty at this point of time. And openpartitions() calls this function too, but it calls syncwithhive() before setting topicpartitionwriters.

Infact not even once we have seen syncwithhive() entering the for loop of ( for (String topic : topics ...) in any case in our tests. could it be issue with partition assignment to the tasks at this point of time ?

Can you please check if you can reproduce this and confirm us.

**Comment by kaushiksrinivas** [comment] 2021-03-18 10:45
Hi @dosvath 
Any insights on this please ?

**Comment by dosvath** [comment] 2021-03-31 19:07
Hi @kaushiksrinivas thank you for bringing up the issue, I am actively looking into this and believe I may have an update for you soon.

**Comment by kaushiksrinivas** [comment] 2021-04-01 05:10
Hi @dosvath 
thanks for taking this up.

**Comment by dosvath** [comment] 2021-04-01 15:41
Hi @kaushiksrinivas, in which version do you see the code working correctly? How did you determine #496 introduced the issue?

**Comment by dosvath** [comment] 2021-04-02 01:18
Hi @kaushiksrinivas do you mean the issue is not present on Confluent platform version `5.4.2`, or on the connector version `5.4.2`? 
I made a `DEBUG` [branch](https://github.com/dosvath/kafka-connect-hdfs/tree/5.4.x-4e68fc09) that is based on connector version `5.3.4` and reverts changes from #496 on top. I still don't see `context.assignment` populated and thus the `syncwithHive` block is still not executed. I'm testing on confluent platform 6.x. I'm guessing the issue may be the difference of handling `start()` and `open()` in the new confluent platform version.

**Comment by kaushiksrinivas** [comment] 2021-04-06 05:15
Hi @dosvath 
I am referring to hdfs sink connector version here and not the confluent version.

in 5.4.2 version and onwards, we do not see the code flow entering the for loop. And the test where it was working / running this code was 5.1.0 in our case. We have not tested all the versions in between 5.1.0 and 5.4.2.

We are not sure if this is the correct behavior or not. If the flow in the for loop highlighted is not run, it will have other hidden issues like we have pointed out above.

**Comment by dosvath** [comment] 2021-04-20 16:48
Thank you @kaushiksrinivas I will be looking into this again this week.

**Comment by dosvath** [comment] 2021-05-19 21:12
Hi @kaushiksrinivas the issue will be fixed by https://github.com/confluentinc/kafka-connect-hdfs/pull/568

**Closed** 2021-05-20 21:12 UTC
