### ISSUE TITLE
Customizable Hive Database and Table names

### ISSUE THREAD

**Issue by vikeshkhanna** [confluentinc/kafka-connect-hdfs#44] opened 2016-03-19 03:57 UTC
Looks like `kafka-connect-hdfs` currently assumes certain values for Hive database (from config) and table names (=topic). Our use case involves reading the database and table names from the Avro Schema (custom properties). To achieve this, we have to fork `TopicPartitionWriter` and `DataWriter` since they directly call hiveMetaStore.addPartition(DB, TABLE,...) and overwrite the DB and TABLE arguments. 
- `DataWriter.java`: https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L262
- `TopicPartitionWriter.java`: https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java#L614

**Comment by vikeshkhanna** [comment] 2016-03-19 04:12
A simple fix would be to have the `addPartition` method in HiveUtil.java base class with the default implementation (just a call to `hiveMetaStore.addPartition(...)`) and replace all instances of `hiveMetaStore.addPartition` with `hive.addPartition`. This allows users to customize the implementation in derived classes. A holistic solution might require cleaning up  `hiveDatabaseName` (or renaming to `hiveDatabaseFromConfig` or something) class member from various places.

**Comment by kkonstantine** [comment] 2017-10-11 22:12
I'm inclined to close this issue, since the root cause of its creation has been addressed with https://github.com/confluentinc/kafka-connect-hdfs/pull/70
Thoughts? /cc @vikeshkhanna @ewencp ?

**Closed** 2018-08-08 22:28 UTC
Labels: enhancement

**Comment by Radeep** [comment] 2018-12-07 14:23
Is it an option to mention custom DB name for Hive instead of using the Kafka topic name.. If this is already covered, could you briefly describe the procedure ..
