### ISSUE TITLE
Slow memory leak in  TopicPartitionWriter   Map<String, Long> offsets 

### ISSUE THREAD

**Issue by patrikni** [confluentinc/kafka-connect-hdfs#233] opened 2017-09-29 08:20 UTC
Hi, 
the offsets map in TopicPartitionWriter is slowly filled by end partition offsets. It`s cleared only during initialization. It is logged to the connector log and runtime with 5 minutes partitions it is increased by 288 items a day.  Unnecessary items should be removed from the map to save heap and disk storage.

Truncated log example with 300 items:
2017-09-29 09:41:37,407 INFO  [pool-1-thread-52] Starting commit and rotation for topic partition ACCOUNT_CORE-3 with start offsets {year=2017/month=09/day=29/hour=09/minute=40/=476397} and end offsets {year=2017/month=09/day=27/hour=10/minute=00/=476130, year=2017/month=09/day=28/hour=17/minute=20/=476365, year=2017/month=09/day=25/hour=17/minute=10/=475842, year=2017/month=09/day=26/hour=17/minute=40/=476056, year=2017/month=09/day=27/hour=14/minute=30/=476238, year=2017/month=09/day=26/hour=10/minute=50/=475923, year=2017/month=09/day=27/hour=08/minute=05/=476078, year=2017/month=09/day=25/hour=16/minute=55/=475833, year=2017/month=09/day=26/hour=14/minute=00/=475992, year=2017/month=09/day=26/hour=12/minute=55/=475970, year=2017/month=09/day=27/hour=12/minute=05/=476195, 
…other 281 items …
year=2017/month=09/day=27/hour=12/minute=30/=476203, year=2017/month=09/day=27/hour=09/minute=50/=476121, year=2017/month=09/day=26/hour=09/minute=50/=475896, year=2017/month=09/day=27/hour=20/minute=15/=476326, year=2017/month=09/day=27/hour=16/minute=40/=476296, year=2017/month=09/day=27/hour=11/minute=15/=476174, year=2017/month=09/day=28/hour=15/minute=25/=476358, year=2017/month=09/day=26/hour=11/minute=15/=475933, year=2017/month=09/day=26/hour=15/minute=25/=476024} (io.confluent.connect.hdfs.TopicPartitionWriter)

**Comment by kkonstantine** [comment] 2017-09-29 17:32
Thanks @patrikni for spotting this! 

Issued https://github.com/confluentinc/kafka-connect-hdfs/pull/235 to fix this.

**Comment by kkonstantine** [comment] 2017-10-02 16:36
Closing, since the root cause was identified and the fix is in. Thanks for reporting the issue @patrikni !

**Closed by kkonstantine** 2017-10-02 16:36 UTC
