### ISSUE TITLE
HDFS connector issue

### ISSUE THREAD

**Issue by amitmalagi** [confluentinc/kafka-connect-hdfs#51] opened 2016-04-20 05:07 UTC
HDFS connector throws this exception and halts execution even if one message in a kafka topic is erroneous. I found that kafka-avro-console-consumer continues with processing of subsequent messages when --skip-message-on-error option is used. Can the same behaviour be provided in HDFS connector?

Thanks.

Exception in thread "WorkerSinkTask-hdfs-sink-0" org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:266)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
        at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 61
Caused by: java.io.EOFException
        at org.apache.avro.io.BinaryDecoder$ByteArrayByteSource.readRaw(BinaryDecoder.java:944)
        at org.apache.avro.io.BinaryDecoder.doReadBytes(BinaryDecoder.java:349)
        at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:263)
        at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201)
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:363)
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:355)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:157)
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:130)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:191)
        at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:130)
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:99)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:266)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:175)

**Comment by jcustenborder** [comment] 2016-04-20 16:03
Hi @amitmalagi I'm not sure we want to skip records on error. Do you have a good idea of how the invalid record entered the topic? What are you using to produce to the topic?

**Comment by amitmalagi** [comment] 2016-04-21 05:04
Hello @jcustenborder, The producer is a node.js application. I am using 'kafka-node' module to post messages to kafka and 'avsc' module to encode messages into arvo format. In some cases, if the message size is bigger than the allocated buffer size used for avro encoding, the resulting record would be invalid.

**Comment by tony-lijinwen** [comment] 2016-08-03 08:15
@amitmalagi, I also encountered the similar issue, did you resolve it?

**Comment by amitmalagi** [comment] 2016-08-04 04:03
@tony-lijinwen, I addressed this issue in our producer application.

**Comment by renukaradhya** [comment] 2016-09-26 09:14
Even I am facing same issue. Please share the fix for the same.

[2016-09-26 13:51:42,569] INFO WorkerSinkTask{id=elasticsearch-schema-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2016-09-26 13:52:34,437] INFO WorkerSinkTask{id=elasticsearch-schema-sink-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2016-09-26 13:52:34,446] ERROR Task elasticsearch-schema-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:357)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

**Comment by Tseretyan** [comment] 2016-09-26 12:16
That error occurrs because your producer application sends messages that are not compatible with consumer. The confluent producer/consumer use some specific format of messages: first byte is 0, then 4 bytes - Id of schema in schema registry (The schema must be registered for the same topic as messages are sent to) and after that - message itself.

**Comment by cotedm** [comment] 2017-01-09 15:38
@Tseretyan is correct and this format is documented [here](http://docs.confluent.io/3.1.1/schema-registry/docs/serializer-formatter.html#wire-format). I'm not seeing anything outstanding here so closing this out.

**Closed by cotedm** 2017-01-09 15:38 UTC
Labels: enhancement
