### ISSUE TITLE
Can't access the maven repo for io.cofluence : Non resolvable parent

### ISSUE THREAD

**Issue by dsvikas** [confluentinc/kafka-connect-hdfs#315] opened 2018-04-13 16:06 UTC
Hi Team, 

I am trying to import kafka-connect-hdfs in my local eclipse. I followed the steps below:

1) Download the source and unzip it
2) Import it in eclipse using "existing maven project" option

But I see a problem related to dependency resolution here. My machine can't connect to maven repository for io.confluence and the error I see is:

[INFO] Scanning for projects...
[WARNING] Could not transfer metadata io.confluent:kafka-connect-storage-common-parent:5.0.0-SNAPSHOT/maven-metadata.xml from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-hdfs:[unknown-version]: Could not transfer artifact io.confluent:kafka-connect-storage-common-parent:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 15, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-connect-hdfs:[unknown-version] (C:\Users\XXXXXX\EclipseWorkspace\kafka-connect-hdfs-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-hdfs:[unknown-version]: Could not transfer artifact io.confluent:kafka-connect-storage-common-parent:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 15, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Has anyone seen a similar issue ? Any suggestions would be highly appreciated.

Vikas

**Comment by cricket007** [comment] 2018-04-13 21:04
Please see https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ

**Comment by cricket007** [comment] 2018-09-11 01:12
@dsvikas Is this still relevant?

**Comment by kkonstantine** [comment] 2018-09-19 04:05
Closing as duplicate of: https://github.com/confluentinc/kafka-connect-hdfs/issues/311
Read this ticket for explanation about build snapshot versions.

**Closed by kkonstantine** 2018-09-19 04:05 UTC
Labels: duplicate
