### ISSUE TITLE
WorkerSinkTask high cpu useage caused by epoll bug

### ISSUE THREAD

**Issue by yzxqc** [confluentinc/kafka-connect-hdfs#277] opened 2018-01-24 12:40 UTC
# Description
Hi,
I see one Connect process cpu usage is over 2000% , but the I/O and network load is very low.
So i find the thread with high cpu.I find some abnormal thread, part of the result is:  
```
USER     %CPU PRI SCNT WCHAN  USER SYSTEM   TID     TIME	
hdfs      0.0  19    - ep_pol    -      - 32301 00:14:50
hdfs      0.0  19    - futex_    -      -   499 00:00:05
hdfs      0.0  19    - futex_    -      -  1060 00:00:24
**hdfs     91.6  19    - -         -      - 24105 2-09:48:19**
hdfs      0.0  19    - futex_    -      -  7111 00:00:39
```
thread 24105   is alaways use 100% cpu, 
thread stacks is : 
```
[hdfs@ha3 root]$ jstack 32111 | grep 5e29 -A 15
"WorkerSinkTask-http_request-connector-2" daemon prio=10 tid=0x00007fe9c4108800 nid=0x5e29 runnable [0x00007fe97931d000]	
	  java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000007482e6388> (a sun.nio.ch.Util$2)
        - locked <0x00000007482e6378> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007482de340> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at org.apache.kafka.common.network.Selector.select(Selector.java:425)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:254)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:270)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:320)
```
About 20 WorkerSinkTask thread is alaways use 100% cpu, 
It seems like jdk **epoll bug** occur in kafka consumer. It caused the consumer cant consume new record and use almost 100% cpu.
I see the latest kafka client version didn't fix the epoll bug.

# How to reproduce
It happened 3 times  in two different environment,  each environment deployd kafka and connect in 3 nodes.
One environment we create 5 topics ,5 connectors,15 tasks,
another we create almost 40 topics ,40 connectors,120 tasks.
There is no effective way to reproduce.
# Checklist
- [ ] Apache Kafka version:0.9.0.0-cp1
- [ ] Confluent Platform:Version 2.0.0
- [ ] JDK version:1.7
- [ ] Centos 7.2 
- [ ] Kernel version :3.10

**Comment by rhauch** [comment] 2018-01-26 15:28
@yzxqc, thanks for logging this issue. However, the HDFS connector (nor really any other Kafka Connect connector) does not directly use the Kafka consumer, and instead relies upon the Kafka Connect framework to do that. So, if this *were* a problem with the Kafka consumer, it should have been logged as such against the Apache Kafka project. However, there have already been issues logged against the Apache Kafka project (see [KAFKA-479](https://issues.apache.org/jira/browse/KAFKA-479?jql=project%20%3D%20KAFKA%20AND%20text%20~%20epoll) for example) that have concluded the problem is actually a Java bug.

Therefore closing this issue.

**Closed by rhauch** 2018-01-26 15:28 UTC
